### ISSUE TITLE
Firing twice on 1st load

### ISSUE THREAD

**Issue by zehawki** [codler/react-ga4#12]
The first time `ReactGA.send({ hitType: "pageview"` is called, 2 events are being sent to GA. From the subsequent time, its only once.

**Comment by cadenzah** [comment]
It seems all events are sent twice as well. Maybe a bug in library, or there should be an option to set a throttling time?

**Comment by cadenzah** [comment]
I guess initializing the GA itself counts as single pageview, so if I use like below, it sends 2 pageview event:
```js
ReactGA.initialize(GA_TRACKING_ID);
ReactGA.send({ hitType: 'pageview', page: window.location.pathname });
```

If I removed the 2nd line, only one pageview event is sent.

**Comment by codler** [comment]
To manually send pageview, initialize with gtagOptions send_page_view false

```js
ReactGA.initialize("your GA measurement id", {
  gtagOptions: {
    send_page_view: false
  }
});

**Comment by EmaAlina** [comment]
Hello,
If we don't have one single page application, we must reset the init and reinitialize the config on each route change.
Is there a way to set the 'send_page_view` flag to `false` without reinitialize RectGA when need this config?

**Comment by steverecio** [comment]
> To manually send pageview, initialize with gtagOptions send_page_view false
> 
> ```js
> ReactGA.initialize("your GA measurement id", {
>   gtagOptions: {
>     send_page_view: false
>   }
> });
> ```

I'm currently doing this but still seeing pages getting automatically tracked. I'm using the following:

```
ReactGA.initialize([
      {
        trackingId: process.env.REACT_APP_GOOGLE_ANALYTICS_GA4_ID,
        gtagOptions: {
          send_page_view: false
        }
      },
      {
        trackingId: process.env.REACT_APP_GOOGLE_ANALYTICS_LEGACY_ID,
      },
    ])
```

**Comment by zehawki** [comment]
I found this to be too much of a headache and switched over to using the GA script directly. Been working just fine since when I raised this issue.
