### ISSUE TITLE
Support the titleCase parameter

### ISSUE THREAD

**Issue by teknolog2000** [codler/react-ga4#15]
There was [a setting in the original ReactGA](https://github.com/react-ga/react-ga#example) for disabling automatic Title case of all event names, and in fact [the format function support it](https://github.com/codler/react-ga4/blob/master/src/format.js#L48) but it is never set to anything but the default true.

My historic events do not use Title case and I'd like to keep it that way so this setting is needed.

**Comment by codler** [comment]
If you change to use [`ReactGA.event(name, params)`](https://github.com/codler/react-ga4#reactgaeventname-params) method signature then it won't convert to title case.

**Comment by teknolog2000** [comment]
Thanks. Would be good to add that to the docs though.

**Comment by sundquistm** [comment]
I would argue we shouldn't presume to reformat a user's parameters unless they opt-in to it.

It's not just about the presentation of data. There could be functionality on the other end of GA reporting that might specifically require a certain formatting.

ReactGA had the same problem where it'd automatically uppercase parameters, though it at least provided an option to turn it off.

With ReactGA4, we have to use a completely different method signature and also document the specific reason why we're doing so.
