### ISSUE TITLE
Support options.gaAddress when initializing?

### ISSUE THREAD

**Issue by toFrankie** [codler/react-ga4#16]
Due to some well-known reasons, `https://www.googletagmanager.com/gtag/js` may not be accessible in China. Can you provide a `gaAddress` option similar to `react-ga`.

Like this:

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/26947203/222100415-68cec422-852a-4711-bf37-6d38ba5201c2.png">

https://github.com/react-ga/react-ga#example

**Comment by codler** [comment]
Added `gtagUrl` option in [v2.1.0](https://github.com/codler/react-ga4/releases/tag/v2.1.0)
