### ISSUE TITLE
Not able to send custom dimension

### ISSUE THREAD

**Issue by mithun-jigsaw** [codler/react-ga4#2]
I'm not able to send my custom dimensions even after adding it. 

My code where I'm adding the custom dimensions
![image](https://user-images.githubusercontent.com/108332738/213670584-751729ac-8061-46f0-b039-3803c962a340.png)
`import ReactGA from 'react-ga4';
const useAnalyticsEventTracker = (category) => {
    const eventTracker = (action, label?, extraDimensions = {}) => {

            console.log("extra dimensions", extraDimensions, action)
            ReactGA.event({ category, action, label, ...extraDimensions });
        }

    }
    return eventTracker;
}

export default useAnalyticsEventTracker;`

The  part which I have highlighted is the object of extra dimensions which I'm sending but it is not getting reflecting the url when I'm sending it. 
![image](https://user-images.githubusercontent.com/108332738/213671049-e7571c35-b824-47f4-b9d6-956e9f20b727.png)

**Comment by codler** [comment]
You will need to add `custom_map` on initialize to send custom dimensions and metrics.
https://developers.google.com/analytics/devguides/collection/gtagjs/custom-dims-mets

```js
ReactGA.initialize("your GA measurement id", {
  gtagOptions: {
    custom_map: {
      dimension1: "dimension1",
      dimension2: "dimension2",
      dimension3: "dimension3", // etc to 200
      metric1: "metric1",
      metric2: "metric2",
      metric4: "metric3", // etc to 200
    }
  }
});
