### ISSUE TITLE
How to send event parameter other than category, action, label, and value ?

### ISSUE THREAD

**Issue by shubhamkr820** [codler/react-ga4#3]
I want to send event parameters other than category, action, label, and value.
For example: `ReactGA.event({category, action, label, value, param1, param2, param3})`.
Is it possible to send or do I have to use Google Tag Manager?
I want similar to this [https://developers.google.com/analytics/devguides/collection/ga4/event-parameters?client_type=gtag#set-up-event-parameters](https://developers.google.com/analytics/devguides/collection/ga4/event-parameters?client_type=gtag#set-up-event-parameters)

**Comment by codler** [comment]
You will need to use the method signature `ReactGA.event(name, params)`

```js
ReactGA.event(action, {
  event_category: category,
  event_label: label, 
  event_value: value, 
  param1, 
  param2, 
  param3
})

**Comment by b-talib-ebs** [comment]
I have sent data in similar style.
I am able to see custom event but not parameters in reports page.
Do I need to use Google Tag Manager?

**Comment by n2k3** [comment]
> I have sent data in similar style. I am able to see custom event but not parameters in reports page. Do I need to use Google Tag Manager?

I seem to have the same issue. Events are visible in Google Analytics dashboard, but no event labels and event values.
