### ISSUE TITLE
Support setting "user_properties" scope

### ISSUE THREAD

**Issue by leo-petrucci** [codler/react-ga4#34]
I've noticed this library doesn't seem to support the [very useful `user_properties` scope](https://support.google.com/analytics/answer/12370404?sjid=15259056839976151146-EU#zippy=%2Cgoogle-tag-websites). Is there a reason why this isn't implemented or would you accept a PR to add it?

I was going to clone the source for my own project to add it, but it'd be far better if it was part of the library itself!

**Comment by MForMarlon** [comment]
@leo-petrucci You should be able to do it via `ReactGA.set({ user_properties: { ... }});`

**Comment by codler** [comment]
```js
ReactGA.gtag('set', 'user_properties', {
  favorite_composer: 'Mahler',
  favorite_instrument: 'double bass',
  season_ticketholder: 'true'
});
