### ISSUE TITLE
Should this track automatically collected events?

### ISSUE THREAD

**Issue by brunomguimaraes** [codler/react-ga4#48]
Hey guys, I'm using this to simply track a pageview on my SPA
But when I pass utm_ params through the url, it doesn't propely track the source/campaign, etc

Here's how I call the `page_view`:
```
ReactGA.event('page_view', {
        page_location: event.share_link,
        page_title: event.name,
});
```
Note that on the `page_location` param I'm passing a custom URL(without the utm's), dunno if that would make a difference

**Comment by rysz-eriksson** [comment]
Hello @brunomguimaraes - how did you manage to solve the problem? I'm also struggling with utm tags not being visible in GA4.
