### ISSUE TITLE
Incorrect number of event sent to Google Analytic

### ISSUE THREAD

**Issue by AsuraKev** [codler/react-ga4#5]
Hi there,

I have an application which has high frequency click of submission. On every submission, we track an event via ReactGA.event(). 
However I noticed that when user clicks fast, the number of xhr request sent to Google is way less than the number of times the button was clicked

1. Click submission 5 time in a row 
2. only one https://www.google-analytics.com/g/collect was fired.

Whats going on? I assume that tracking is synchronous given ReactGA.event() doesnt return a promise

**Comment by codler** [comment]
`most events are grouped together (or batched)`
https://support.google.com/analytics/answer/9322688?hl=en
