### ISSUE TITLE
ReactGA.event sending to analytics with category first letter uppercase

### ISSUE THREAD

**Issue by almasshaikh08** [codler/react-ga4#54]
I start sending events to google analytics using this package, but start seeing the category with the first letter in uppercase.

Is there something related to the package? Because before using it, I effectively send events to google analytics without the first letter in uppercase. This issue was fixed in react-ga by making titleCase option to false. Can you please provide titleCase option.

My code:

`ReactGA.event({
      category: 'mycategory',
      action: 'click',
      label: 'mylabel'
    });`

And in google analytics it appear like:

Mycategory and with action Click.

**Comment by jeromecovington** [comment]
I would like the option to set `titleCase` to `false` as well.

**Comment by ospaarmann** [comment]
Is there any update on this, @codler? Are you still maintaining this repo? Thanks!

**Comment by elamperti** [comment]
@ospaarmann I've created [a fork](https://github.com/elamperti/react-ga-neo) with this, a few other of the pending PRs and a few code improvements. It's available on npm as [`react-ga-neo`](https://www.npmjs.com/package/react-ga-neo) as well.

**Comment by codler** [comment]
Duplicate #39 #15

**Comment by elamperti** [comment]
Why did you delete my comment @codler?
