### ISSUE TITLE
how to send user scope parameter?

### ISSUE THREAD

**Issue by IsaacBruno** [codler/react-ga4#7]
I want to send a user scope param such as userId.
Should I use `ReactGA.event({category, action, label, value, userId})` or `ReactGA.set({userId})`?
![image](https://user-images.githubusercontent.com/10129641/216980777-92983645-fc44-407f-9aba-21dd8a47b0b7.png)

**Comment by codler** [comment]
https://developers.google.com/analytics/devguides/collection/ga4/user-id?client_type=gtag

```js
ReactGA.gtag('config', 'TAG_ID', {
  'user_id': 'USER_ID'
});
